---
- name: An Ansible Playbook example for AWX
  hosts: demo
  tasks:
    - name: Display all variables/facts known for a host
      debug:
      var: hostvars[inventory_hostname]
      verbosity: 4
