---
- name: An Ansible Playbook example for AWX
  hosts: "{{ remote_name }}"
  tasks:
    - name: Check Latency
      ansible.builtin.command: traceroute "{{ hostname }}"
      register: command_output

    - debug:
        var: command_output.stdout_lines
