---
- name: Speedtest for {{ remote_name }}
  hosts: "{{ remote_name }}"
  tasks:
    - name: Check Speed
      docker_container:
        name: speedtest
        image: "crazyuploader/speedtest"
      register: speedtest_output

    - name: Show speedtest output
      debug:
        var: "{{ speedtest_output.ansible_facts.docker_container.Output }}"
