---
- name: Speedtest for {{ remote_name }}
  hosts: "{{ remote_name }}"
  tasks:
    - name: Check Speedtest
      ansible.builtin.command: docker run crazyuploader/speedtest:latest
      register: command_output

    - debug:
        var: command_output.stdout_lines
