---
- name: Speedtest for {{ remote_name }}
  hosts: "{{ remote_name }}"
  tasks:
    - name: Start a container with a command
      community.docker.docker_container:
        name: sleepy
        image: ubuntu:latest
        command: ["sleep", "infinity"]
